from __future__ import annotations

import threading
import time
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from devflow.database import Database
from devflow.docker_runner import candidate_runner_from_environment
from devflow.errors import InvalidRunTransition, RevisionConflict
from devflow.mock_provider import DeterministicMockProvider
from devflow.models import CreateRunRequest, DecisionKind, FilePatchSet, RunStatus, WorkflowState
from devflow.pipeline import RunPipeline
from devflow.workflow import build_graph, invoke_resume, invoke_start, open_graph
from devflow.workspace import ManagedWorkspace


class _DecisionResumeLeaseLost(InvalidRunTransition):
    pass


class RunCoordinator:
    DECISION_LEASE_SECONDS = 30
    DECISION_POLL_SECONDS = 0.01

    def __init__(
        self, database_path: Path | str, workspace_root: Path | str | None = None,
        *, provider=None, runner=None, recover=True,
    ):
        self.database = Database(database_path)
        self.database.initialize()
        self.workspace = ManagedWorkspace(
            workspace_root or self.database.path.parent / "workspaces" / "default",
            self.database,
        )
        self.workspace.initialize()
        self.pipeline = RunPipeline(
            self.database, self.workspace,
            provider or DeterministicMockProvider(), runner or candidate_runner_from_environment(),
        )
        self._recovery_schedule_lock = threading.Lock()
        self._scheduled_recoveries: set[str] = set()
        if recover:
            self._recover_incomplete_starts()
            self._recover_incomplete_decisions()

    def start(
        self,
        *,
        run_id: str,
        patch_id: str,
        patch_revision: int = 1,
        candidate_dir: str | None = None,
        patch: dict[str, Any] | None = None,
        task: str = "Demonstrate the deterministic coding workflow",
    ) -> dict[str, Any]:
        task = CreateRunRequest(task=task).task
        if patch is not None:
            raise ValueError("patches must be generated by the Coder stage")
        thread_id = run_id
        candidate_path = self.workspace.candidate_path(run_id)
        if candidate_dir is not None:
            candidate_path = self.workspace.require_candidate_path(run_id, candidate_dir)
        self.database.create_run(
            run_id=run_id,
            thread_id=thread_id,
            patch_id=patch_id,
            patch_revision=patch_revision,
            candidate_dir=str(candidate_path),
            patch={"files": []},
            task=task,
        )
        return self.execute_existing(run_id)

    def workspace_for(self, run_id: str) -> ManagedWorkspace:
        workspace_id = self.database.get_run(run_id)["workspace_id"]
        if workspace_id == "default":
            return self.workspace
        if workspace_id != run_id:
            raise ValueError("invalid task workspace identity")
        root = self.workspace.root.parent / workspace_id
        return ManagedWorkspace(root, self.database)

    def execute_existing(self, run_id: str, *, defer_finish: bool = False) -> dict[str, Any]:
        run = self.database.get_run(run_id)
        patch_row = self.database.current_patch(run_id)
        patch_id = patch_row["id"]
        patch_revision = patch_row["patch_revision"]
        thread_id = run["thread_id"]
        task = self.database.artifacts(run_id)["task"]
        try:
            workspace = self.workspace_for(run_id)
            pipeline = (self.pipeline if workspace is self.workspace else
                        RunPipeline(self.database, workspace, self.pipeline.provider, self.pipeline.runner))
            state = WorkflowState(
                run_id=run_id,
                thread_id=thread_id,
                patch_id=patch_id,
                patch_revision=patch_revision,
                base_workspace_revision=int(run["base_workspace_revision"]),
                task=task,
                provider=self.database.context(run_id).get("provider", "mock"),
            )
            with open_graph(self.database.path) as checkpointer:
                graph = build_graph(checkpointer, pipeline)
                try:
                    result = invoke_start(graph, state, thread_id)
                except Exception:
                    # Node failures also leave durable diagnostic checkpoints.
                    # An invocation that never started has no checkpoint to save.
                    self._save_checkpoint_ref(graph, run_id, thread_id, required=False)
                    raise
                self._save_checkpoint_ref(graph, run_id, thread_id)
            if result.get("status") == RunStatus.FAILED:
                if defer_finish:
                    self.database.update_context(run_id, execution_outcome="failed")
                else:
                    self.database.fail_run_start(run_id)
                return self.snapshot(run_id)
            if "__interrupt__" not in result:
                raise RuntimeError("workflow did not stop at the approval interrupt")
            if defer_finish:
                self.database.update_context(run_id, execution_outcome="approval")
            else:
                self.database.mark_awaiting_approval(run_id)
        except Exception:
            self.database.execution_error(run_id, "execution_failed", "Execution failed; inspect the completed stage reports.", finalize=not defer_finish)
            if not defer_finish:
                self.database.fail_run_start(run_id)
            raise
        return self.snapshot(run_id)

    def decide(
        self,
        *,
        run_id: str,
        patch_revision: int,
        decision_id: str,
        kind: DecisionKind,
        feedback: str | None = None,
    ) -> dict[str, Any]:
        try:
            row = self.database.get_patch(run_id, patch_revision)
        except KeyError as error:
            raise RevisionConflict("patch revision does not exist for this run") from error
        run = self.database.get_run(run_id)
        # This synchronous slice has no cooperative in-flight cancellation.
        # Reject early decisions before parsing CODE's ungenerated placeholder.
        if RunStatus(run["status"]) in {RunStatus.CREATED, RunStatus.RUNNING}:
            raise InvalidRunTransition("decisions require AWAITING_APPROVAL status")
        patch_set = FilePatchSet.model_validate_json(row["patch_json"])
        if kind is DecisionKind.APPROVE and RunStatus(run["status"]) is RunStatus.AWAITING_APPROVAL:
            self.workspace_for(run_id).require_materialized_candidate(run_id, row["candidate_dir"])
        _decision, _created = self.database.record_decision(
            decision_id=decision_id,
            run_id=run_id,
            patch_revision=patch_revision,
            kind=kind,
            feedback=feedback,
        )
        owner_id = uuid.uuid4().hex
        while True:
            claim = self.database.claim_decision_resume(
                decision_id=decision_id,
                owner_id=owner_id,
                lease_seconds=self.DECISION_LEASE_SECONDS,
            )
            if claim == "completed":
                return self.snapshot(run_id)
            if claim == "acquired":
                break
            time.sleep(self.DECISION_POLL_SECONDS)

        resume_started = False
        try:
            run = self.database.get_run(run_id)
            with self._keep_decision_claim_alive(decision_id, owner_id) as ensure_claim:
                if kind is DecisionKind.APPROVE:
                    self._require_unpublished_candidate(
                        run_id, patch_revision, decision_id, owner_id
                    )
                with open_graph(self.database.path) as checkpointer:
                    publish = None
                    if kind is DecisionKind.APPROVE:
                        publish = lambda state: self.workspace_for(run_id).publish_patch(
                            decision_id=decision_id, owner_id=owner_id, run_id=run_id,
                            patch=state.patch or patch_set,
                        )
                    graph = build_graph(checkpointer, resume_guard=ensure_claim, publish=publish)
                    ensure_claim()
                    resume_started = True
                    result = invoke_resume(
                        graph,
                        thread_id=run["thread_id"],
                        decision_id=decision_id,
                        kind=kind,
                    )
                    ensure_claim()
                    self._save_checkpoint_ref(graph, run_id, run["thread_id"])
                final_status = RunStatus(result["status"])
                expected = {
                    DecisionKind.APPROVE: RunStatus.COMPLETE,
                    DecisionKind.REJECT: RunStatus.REJECTED,
                    DecisionKind.CANCEL: RunStatus.CANCELED,
                }[kind]
                if final_status is not expected:
                    raise RuntimeError(
                        f"workflow finished in {final_status.value}; expected {expected.value}"
                    )
                ensure_claim()
                self.database.finish_decision(decision_id, final_status, owner_id=owner_id)
        except _DecisionResumeLeaseLost:
            if kind is DecisionKind.APPROVE:
                self.database.fail_decision(
                    decision_id,
                    reason="decision resume lease renewal failed",
                    owner_id=owner_id,
                )
            self.database.release_decision_resume_claim(
                decision_id=decision_id, owner_id=owner_id
            )
            raise
        except Exception:
            self.database.release_decision_resume_claim(
                decision_id=decision_id, owner_id=owner_id
            )
            if resume_started:
                # A persisted decision whose resume began must remain eligible
                # for asynchronous reconciliation after transient failures.
                self._schedule_decision_recovery(
                    decision_id, self.DECISION_LEASE_SECONDS
                )
            raise
        return self.snapshot(run_id)

    def _require_unpublished_candidate(
        self, run_id: str, patch_revision: int, decision_id: str, owner_id: str
    ) -> None:
        # A committed publication needs only checkpoint/status reconciliation:
        # publish_patch returns its existing revision without writing again.
        # Before that commit, both resume entry points retain candidate checks.
        if self.database.publication_for_decision(decision_id) is not None:
            return
        patch = self.database.get_patch(run_id, patch_revision)
        try:
            self.workspace_for(run_id).require_materialized_candidate(run_id, patch["candidate_dir"])
        except Exception as error:
            self.database.fail_decision(
                decision_id,
                reason=f"candidate validation failed: {type(error).__name__}: {error}",
                owner_id=owner_id,
            )
            raise

    @contextmanager
    def _keep_decision_claim_alive(self, decision_id: str, owner_id: str):
        stopped = threading.Event()
        claim_lost = threading.Event()

        def renew_claim() -> bool:
            try:
                renewed = self.database.renew_decision_resume_claim(
                    decision_id=decision_id,
                    owner_id=owner_id,
                    lease_seconds=self.DECISION_LEASE_SECONDS,
                )
            except Exception:  # noqa: BLE001 - loss is enforced by the resume guard
                renewed = False
            if not renewed:
                claim_lost.set()
            return renewed

        def ensure_claim() -> None:
            if claim_lost.is_set() or not renew_claim():
                raise _DecisionResumeLeaseLost("decision resume lease renewal failed")

        def renew() -> None:
            interval = self.DECISION_LEASE_SECONDS / 3
            while not stopped.wait(interval):
                if not renew_claim():
                    return

        heartbeat = threading.Thread(target=renew, daemon=True)
        heartbeat.start()
        try:
            yield ensure_claim
        finally:
            stopped.set()
            heartbeat.join(timeout=1)

    def snapshot(self, run_id: str) -> dict[str, Any]:
        return self.database.snapshot(run_id)

    def _recover_incomplete_starts(self) -> None:
        for run in self.database.list_runs_with_status(RunStatus.RUNNING):
            if self.database.context(run["id"]).get("cleanup_pending"):
                continue
            recovered = False
            try:
                with open_graph(self.database.path) as checkpointer:
                    graph = build_graph(checkpointer)
                    snapshot = graph.get_state(
                        {"configurable": {"thread_id": run["thread_id"]}}
                    )
                    values = snapshot.values
                    if (
                        values
                        and values.get("run_id") == run["id"]
                        and "await_approval" in snapshot.next
                    ):
                        patch = self.database.get_patch(
                            run["id"], int(values["patch_revision"])
                        )
                        self.workspace_for(run["id"]).require_materialized_candidate(
                            run["id"], patch["candidate_dir"]
                        )
                        self._save_checkpoint_ref(graph, run["id"], run["thread_id"])
                        self.database.mark_awaiting_approval(run["id"])
                        recovered = True
            except Exception:  # noqa: BLE001 - startup reconciliation is a recovery boundary
                recovered = False
            if not recovered:
                self.database.fail_run_start(run["id"])

    def _recover_incomplete_decisions(self) -> None:
        """Reconcile decisions recorded before resume finalization."""
        runs = [
            *self.database.list_runs_with_status(RunStatus.APPLYING),
            *self.database.list_runs_with_status(RunStatus.REJECTED),
            *self.database.list_runs_with_status(RunStatus.CANCELED),
        ]
        for run in runs:
            decisions = self.database.list_unfinished_decisions(run["id"])
            if len(decisions) != 1:
                if decisions and RunStatus(run["status"]) is RunStatus.APPLYING:
                    self.database.fail_decision(
                        decisions[0]["decision_id"], reason="ambiguous incomplete decision"
                    )
                elif not decisions and RunStatus(run["status"]) is RunStatus.APPLYING:
                    self.database.fail_applying_run(
                        run["id"], reason="APPLYING run has no incomplete decision"
                    )
                continue
            decision = decisions[0]
            expected = {
                DecisionKind.APPROVE: RunStatus.COMPLETE,
                DecisionKind.REJECT: RunStatus.REJECTED,
                DecisionKind.CANCEL: RunStatus.CANCELED,
            }[DecisionKind(decision["kind"])]
            owner_id = uuid.uuid4().hex
            claim_busy = False
            try:
                with open_graph(self.database.path) as checkpointer:
                    claim = self.database.claim_decision_resume(
                        decision_id=decision["decision_id"],
                        owner_id=owner_id,
                        lease_seconds=self.DECISION_LEASE_SECONDS,
                    )
                    if claim == "busy":
                        claim_busy = True
                        self._schedule_decision_recovery(
                            decision["decision_id"],
                            self.database.decision_resume_lease_remaining(decision["decision_id"]),
                        )
                    elif claim == "acquired":
                        with self._keep_decision_claim_alive(
                            decision["decision_id"], owner_id
                        ) as ensure_claim:
                            ensure_claim()
                            if DecisionKind(decision["kind"]) is DecisionKind.APPROVE:
                                self._require_unpublished_candidate(
                                    run["id"], int(decision["patch_revision"]),
                                    decision["decision_id"], owner_id,
                                )
                            graph = build_graph(checkpointer, resume_guard=ensure_claim)
                            # Read recovery state only after acquiring the resume lease.
                            snapshot = graph.get_state(
                                {"configurable": {"thread_id": run["thread_id"]}}
                            )
                            if not snapshot.next and RunStatus(snapshot.values.get("status")) is expected:
                                self.database.finish_decision(
                                    decision["decision_id"], expected, owner_id=owner_id
                                )
                            elif DecisionKind(decision["kind"]) in (DecisionKind.REJECT, DecisionKind.CANCEL):
                                # Reject/cancel are already durable in the DB, but their graph
                                # resume may not have happened before the crash.
                                result = invoke_resume(
                                    graph,
                                    thread_id=run["thread_id"],
                                    decision_id=decision["decision_id"],
                                    kind=DecisionKind(decision["kind"]),
                                )
                                ensure_claim()
                                self._save_checkpoint_ref(graph, run["id"], run["thread_id"])
                                if RunStatus(result["status"]) is expected:
                                    self.database.finish_decision(
                                        decision["decision_id"], expected, owner_id=owner_id
                                    )
                            elif DecisionKind(decision["kind"]) is DecisionKind.APPROVE:
                                patch_row = self.database.get_patch(run["id"], int(decision["patch_revision"]))
                                recovery_graph = build_graph(
                                    checkpointer,
                                    resume_guard=ensure_claim,
                                    publish=lambda state, decision_id=decision["decision_id"], owner_id=owner_id,
                                        run_id=run["id"], patch_json=patch_row["patch_json"]: self.workspace_for(run_id).publish_patch(
                                        decision_id=decision_id, owner_id=owner_id,
                                        run_id=run_id, patch=state.patch or FilePatchSet.model_validate_json(patch_json),
                                    ),
                                )
                                result = invoke_resume(
                                    recovery_graph, thread_id=run["thread_id"],
                                    decision_id=decision["decision_id"], kind=DecisionKind.APPROVE,
                                )
                                ensure_claim()
                                self._save_checkpoint_ref(recovery_graph, run["id"], run["thread_id"])
                                if RunStatus(result["status"]) is expected:
                                    self.database.finish_decision(
                                        decision["decision_id"], expected, owner_id=owner_id
                                    )
            except Exception:  # noqa: BLE001 - recovery boundary must preserve live leases
                if not self.database.list_unfinished_decisions(run["id"]):
                    # Candidate validation can durably fail an unpublished decision.
                    continue
                # A live lease belongs to another worker; never turn it into failure.
                delay = self.database.decision_resume_lease_remaining(decision["decision_id"])
                self._schedule_decision_recovery(
                    decision["decision_id"],
                    delay if delay > 0 else self.DECISION_LEASE_SECONDS,
                )
                continue
            if claim_busy:
                continue
            # Non-terminal checkpoints are only safely failed for approvals, whose
            # durable APPLYING state is the recovery lock. Rejects already expose a
            # terminal status and must remain retryable until their resume completes.
            if RunStatus(run["status"]) is RunStatus.APPLYING:
                with self.database.connect() as connection:
                    pending = connection.execute(
                        "SELECT resume_completed_at FROM decisions WHERE decision_id = ?",
                        (decision["decision_id"],),
                    ).fetchone()
                if pending and pending["resume_completed_at"] is None:
                    self.database.fail_decision(
                        decision["decision_id"],
                        reason="resume did not reach a durable terminal checkpoint",
                        owner_id=owner_id,
                    )

    def _schedule_decision_recovery(self, decision_id: str, delay: float) -> None:
        delay = max(0.01, delay + 0.01)
        with self._recovery_schedule_lock:
            if decision_id in self._scheduled_recoveries:
                return
            self._scheduled_recoveries.add(decision_id)
        timer = threading.Timer(delay, self._run_scheduled_recovery, args=(decision_id,))
        timer.daemon = True
        timer.start()

    def _run_scheduled_recovery(self, decision_id: str) -> None:
        with self._recovery_schedule_lock:
            self._scheduled_recoveries.discard(decision_id)
        try:
            self._recover_incomplete_decisions()
        except Exception:  # noqa: BLE001 - retry must not terminate the worker
            self._schedule_decision_recovery(decision_id, self.DECISION_LEASE_SECONDS)

    def _save_checkpoint_ref(self, graph, run_id: str, thread_id: str, *, required=True) -> None:
        snapshot = graph.get_state({"configurable": {"thread_id": thread_id}})
        configurable = snapshot.config.get("configurable", {})
        checkpoint_id = configurable.get("checkpoint_id")
        if not checkpoint_id:
            if required:
                raise RuntimeError("LangGraph did not return a durable checkpoint id")
            return
        self.database.save_checkpoint_ref(
            run_id=run_id,
            thread_id=thread_id,
            checkpoint_ns=str(configurable.get("checkpoint_ns", "")),
            checkpoint_id=str(checkpoint_id),
        )
